version: "3"
services:
  active_mq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
  camel_database:
    image: mysql:8.0.25
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: camel@123
      MYSQL_DATABASE: camel
      MYSQL_USER: camel
      MYSQL_PASSWORD: camel@123
